on:
    push:
      branches:
        - main
        - ci_test
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v5
        with:
          workflow: "CI.yaml"
          branch: ${{ github.ref }}
          name: wheels-linux-x86_64
          path: wheels/
      - name: "Install packages"
        run: |
          pip install -U sphinx sphinx_rtd_theme
          pip install wheels/*.whl
      - name: "Build docs"
        working-directory: docs
        run: sphinx-build -b html source build
      - name: Fix permissions
        run: |
          chmod -c -R +rX "docs/build/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build

  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: docs

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: read
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action


  
  
          